"""
Unified Overlay Backtest - v9.33

Walk-forward backtest validation for the UNIFIED_OVERLAY signal
(15% weight in ensemble voter, activated v9.31 from dead code).

The UNIFIED_OVERLAY is generated by OrchestratorEnsembleBridge which
converts UnifiedOrchestrator's 7-asset allocation recommendation into
a directional signal (-1 to +1). The orchestrator combines:
  - Collar overlay (20% weight) — VIX-gated equity protection
  - Bond duration rotation (25%) — yield curve regime shifts
  - Crypto tactical (15%) — BTC/ETH momentum
  - Calendar seasonality (10%) — execution timing
  - VIXY hedge sizing (5%) — volatility hedging

This backtest simulates the overlay on historical data (2006-2026)
by reconstructing the signal from VIX levels and price momentum,
then measuring Sharpe delta vs the baseline 46/38/16 allocation.

Target: Validate that UNIFIED_OVERLAY adds alpha (Sharpe >= baseline).
"""

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from src.backtest.metrics import (
    BacktestConfig as _BaseConfig,
    BacktestResult,
    compute_metrics,
    save_results_json,
)
from src.paths import PRICES_JSON, BACKTEST_RESULTS_DIR


__all__ = ['BacktestConfig', 'DailyData', 'UnifiedOverlayBacktester']

logger = logging.getLogger(__name__)


@dataclass
class BacktestConfig(_BaseConfig):
    """Configuration for unified overlay backtest.

    Inherits canonical fields (start_date, end_date, initial_capital,
    base_weights, rebalance_frequency_days, transaction_cost_bps) from
    :class:`_BaseConfig`.  Backtest-specific fields are defined here.
    """

    # Overlay shift limits (from UnifiedOrchestrator hard bounds)
    max_spy_shift: float = 0.10
    max_gld_shift: float = 0.10
    max_bond_shift: float = 0.10
    max_crypto: float = 0.05

    # VIX thresholds (from UnifiedOrchestrator v9.15)
    vix_collar_max: float = 30.0
    vix_vixy_min: float = 20.0
    vix_crisis: float = 40.0


@dataclass
class DailyData:
    """Single day return data."""
    date: str
    spy_return: float
    gld_return: float
    tlt_return: float
    vix_level: Optional[float] = None


class UnifiedOverlayBacktester:
    """Walk-forward backtest for the unified overlay signal."""

    def __init__(self, config: Optional[BacktestConfig] = None):
        self.config = config or BacktestConfig()
        self.data: List[DailyData] = []
        self.prices_raw: Dict = {}

    # ------------------------------------------------------------------
    # Data loading
    # ------------------------------------------------------------------
    def load_data(self, data_path: Optional[str] = None) -> bool:
        """Load price data from PRICES_JSON."""
        try:
            prices_path = PRICES_JSON
            if not prices_path.exists():
                logger.error("Price data not found")
                return False

            with open(prices_path) as f:
                self.prices_raw = json.load(f)

            self._process_price_data()
            logger.info("Loaded %d days of price data", len(self.data))
            return True

        except (OSError, json.JSONDecodeError, KeyError, ValueError, TypeError) as exc:
            logger.error("Failed to load data: %s", exc)
            return False

    def _process_price_data(self) -> None:
        """Build DailyData list from raw price dicts."""
        spy = self.prices_raw.get("SPY", [])
        gld = self.prices_raw.get("GLD", [])
        tlt = self.prices_raw.get("TLT", [])

        if not spy:
            logger.error("No SPY data found")
            return

        vix = self.prices_raw.get("^VIX", [])
        vix_px = {p["d"]: p["p"] for p in vix} if vix else {}

        # If no VIX data, compute VIX proxy from SPY realized vol
        self._vix_proxy = {}
        if not vix_px:
            spy_prices_list = sorted(
                self.prices_raw.get("SPY", []), key=lambda x: x["d"]
            )
            if len(spy_prices_list) > 22:
                for j in range(21, len(spy_prices_list)):
                    window = spy_prices_list[j-21:j+1]
                    if len(window) == 22:
                        rets = [(window[k+1]["p"] / window[k]["p"] - 1) for k in range(21)]
                        vol = np.std(rets) * np.sqrt(252) * 100  # Annualized vol %
                        # VIX proxy: realized vol * 1.1 (VIX typically > realized)
                        self._vix_proxy[spy_prices_list[j]["d"]] = vol * 1.1

        dates = [p["d"] for p in spy]
        spy_px = {p["d"]: p["p"] for p in spy}
        gld_px = {p["d"]: p["p"] for p in gld}
        tlt_px = {p["d"]: p["p"] for p in tlt}

        cfg = self.config
        for i, date in enumerate(dates[1:], 1):
            if date < cfg.start_date or date > cfg.end_date:
                continue

            prev = dates[i - 1]
            s_p, s_c = spy_px.get(prev), spy_px.get(date)
            g_p, g_c = gld_px.get(prev), gld_px.get(date)
            t_p, t_c = tlt_px.get(prev), tlt_px.get(date)

            if all(v is not None for v in (s_p, s_c, g_p, g_c, t_p, t_c)):
                self.data.append(DailyData(
                    date=date,
                    spy_return=(s_c - s_p) / s_p,
                    gld_return=(g_c - g_p) / g_p,
                    tlt_return=(t_c - t_p) / t_p,
                    vix_level=vix_px.get(date) or self._vix_proxy.get(prev),
                ))

    # ------------------------------------------------------------------
    # Signal computation — reconstruct each sub-overlay from price data
    # ------------------------------------------------------------------
    def _compute_collar_signal(self, vix: Optional[float]) -> Tuple[float, float, float]:
        """Collar overlay: protects equity via OTM put, VIX-gated."""
        if vix is None or vix > self.config.vix_collar_max:
            return 0.0, 0.0, 0.0
        # Active collar: slight SPY reduction (premium cost), TLT increase
        collar_intensity = max(0.0, 1.0 - vix / self.config.vix_collar_max)
        return -0.01 * collar_intensity, 0.0, 0.01 * collar_intensity

    def _compute_vixy_signal(self, vix: Optional[float]) -> Tuple[float, float, float]:
        """VIXY hedge: vol-based hedge, VIX-gated."""
        if vix is None or vix < self.config.vix_vixy_min:
            return 0.0, 0.0, 0.0
        # VIXY allocation = VIX/10%, funded from SPY
        vixy_alloc = min(vix / 10.0, 10.0) / 100.0
        vixy_alloc = min(vixy_alloc, 0.06)
        return -vixy_alloc, 0.0, 0.0

    def _compute_bond_duration_signal(self, tlt_prices: List[Dict],
                                       end_idx: int) -> Tuple[float, float, float]:
        """Bond duration rotation based on yield curve proxy."""
        if end_idx < 60 or end_idx >= len(tlt_prices):
            return 0.0, 0.0, 0.0

        recent = tlt_prices[max(0, end_idx - 60):end_idx + 1]
        if len(recent) < 20:
            return 0.0, 0.0, 0.0

        tlt_momentum = (recent[-1]["p"] / recent[0]["p"]) - 1.0

        if tlt_momentum > 0.05:
            return 0.0, -0.01, 0.01
        elif tlt_momentum < -0.05:
            return 0.0, 0.01, -0.01
        return 0.0, 0.0, 0.0

    def _compute_crypto_signal(self, spy_prices: List[Dict],
                                end_idx: int) -> Tuple[float, float, float, float]:
        """Crypto tactical: BTC/ETH momentum, funded from GLD."""
        if end_idx < 130 or end_idx >= len(spy_prices):
            return 0.0, 0.0, 0.0, 0.0

        recent = spy_prices[max(0, end_idx - 130):end_idx + 1]
        if len(recent) < 20:
            return 0.0, 0.0, 0.0, 0.0

        mom_6m = (recent[-1]["p"] / recent[0]["p"]) - 1.0

        if mom_6m > 0.0:
            crypto_alloc = min(mom_6m * 0.05, self.config.max_crypto)
            return 0.0, -crypto_alloc, 0.0, crypto_alloc
        return 0.0, 0.0, 0.0, 0.0

    # ------------------------------------------------------------------
    # Backtest execution
    # ------------------------------------------------------------------
    def run(self) -> BacktestResult:
        """Run the full walk-forward backtest."""
        empty_result = BacktestResult(
            total_return=0, cagr=0, volatility=0, sharpe_ratio=0,
            max_drawdown=0, baseline_sharpe=0, sharpe_improvement=0,
            total_rebalances=0, total_transaction_costs=0,
            extras={
                "overlay_active_days": 0, "overlay_active_pct": 0,
                "collar_active_days": 0, "vixy_active_days": 0,
                "crypto_active_days": 0, "bond_duration_active_days": 0,
            },
        )

        if not self.data:
            logger.error("No data loaded. Call load_data() first.")
            return empty_result

        cfg = self.config

        # Build equity curves
        baseline_curve = [cfg.initial_capital]
        overlay_curve = [cfg.initial_capital]

        baseline_weights = dict(cfg.base_weights)
        overlay_weights = dict(baseline_weights)

        # Overlay stats
        overlay_active_days = 0
        collar_active = 0
        vixy_active = 0
        crypto_active = 0
        bond_dur_active = 0
        total_rebalances = 0
        total_costs = 0.0
        equity_curve_sampled = []

        # Price data for signal computation
        spy_prices = sorted(self.prices_raw.get("SPY", []), key=lambda x: x["d"])
        tlt_prices = sorted(self.prices_raw.get("TLT", []), key=lambda x: x["d"])

        # Crisis return tracking
        crisis_daily_returns = {"2008": [], "2020": [], "2022": []}

        for i, day in enumerate(self.data):
            # --- Compute overlay allocation shifts ---
            spy_delta = 0.0
            gld_delta = 0.0
            tlt_delta = 0.0
            crypto_alloc = 0.0
            any_active = False

            # 1. Collar
            c_spy, c_gld, c_tlt = self._compute_collar_signal(day.vix_level)
            if c_spy != 0 or c_tlt != 0:
                collar_active += 1
                any_active = True
            spy_delta += c_spy
            gld_delta += c_gld
            tlt_delta += c_tlt

            # 2. VIXY hedge
            v_spy, v_gld, v_tlt = self._compute_vixy_signal(day.vix_level)
            if v_spy != 0:
                vixy_active += 1
                any_active = True
            spy_delta += v_spy
            gld_delta += v_gld
            tlt_delta += v_tlt

            # 3. Bond duration rotation
            end_idx = min(i, len(tlt_prices) - 1)
            b_spy, b_gld, b_tlt = self._compute_bond_duration_signal(tlt_prices, end_idx)
            if b_gld != 0 or b_tlt != 0:
                bond_dur_active += 1
                any_active = True
            spy_delta += b_spy
            gld_delta += b_gld
            tlt_delta += b_tlt

            # 4. Crypto tactical
            end_idx_spy = min(i, len(spy_prices) - 1)
            cr_spy, cr_gld, cr_tlt, cr_total = self._compute_crypto_signal(
                spy_prices, end_idx_spy
            )
            if cr_total > 0:
                crypto_active += 1
                any_active = True
            spy_delta += cr_spy
            gld_delta += cr_gld
            tlt_delta += cr_tlt
            crypto_alloc = cr_total

            if any_active:
                overlay_active_days += 1

            # --- Apply hard constraints ---
            new_spy = float(np.clip(cfg.base_weights['SPY'] + spy_delta, 0.36, 0.56))
            new_gld = float(np.clip(cfg.base_weights['GLD'] + gld_delta, 0.28, 0.48))
            new_tlt = float(np.clip(cfg.base_weights['TLT'] + tlt_delta, 0.0, 0.20))
            crypto_alloc = min(crypto_alloc, cfg.max_crypto)

            # Renormalize
            non_crypto = 1.0 - crypto_alloc
            total_base = new_spy + new_gld + new_tlt
            if total_base > 0:
                scale = non_crypto / total_base
                new_spy *= scale
                new_gld *= scale
                new_tlt *= scale
            else:
                new_spy = cfg.base_weights['SPY'] * non_crypto
                new_gld = cfg.base_weights['GLD'] * non_crypto
                new_tlt = cfg.base_weights['TLT'] * non_crypto

            overlay_weights = {"SPY": new_spy, "GLD": new_gld, "TLT": new_tlt}

            # --- Rebalance on schedule ---
            if i % cfg.rebalance_frequency_days == 0:
                total_rebalances += 1
                for key in overlay_weights:
                    delta_w = abs(overlay_weights[key] - baseline_weights[key])
                    total_costs += delta_w * overlay_curve[-1] * cfg.transaction_cost_bps / 10000

            # --- Compute daily returns ---
            baseline_ret = (
                baseline_weights["SPY"] * day.spy_return +
                baseline_weights["GLD"] * day.gld_return +
                baseline_weights["TLT"] * day.tlt_return
            )

            # Crypto gets 1.5x SPY return as proxy
            crypto_ret = day.spy_return * 1.5
            overlay_ret = (
                overlay_weights["SPY"] * day.spy_return +
                overlay_weights["GLD"] * day.gld_return +
                overlay_weights["TLT"] * day.tlt_return +
                crypto_alloc * crypto_ret
            )

            baseline_curve.append(baseline_curve[-1] * (1 + baseline_ret))
            overlay_curve.append(overlay_curve[-1] * (1 + overlay_ret))

            # Crisis tracking
            for year in crisis_daily_returns:
                if day.date.startswith(year):
                    crisis_daily_returns[year].append(overlay_ret)

            # Sample equity curve monthly
            if i % 21 == 0:
                equity_curve_sampled.append({
                    "date": day.date,
                    "baseline": round(baseline_curve[-1], 2),
                    "overlay": round(overlay_curve[-1], 2),
                })

        # --- Compute metrics ---
        baseline_metrics = compute_metrics(baseline_curve, cfg.initial_capital)
        overlay_metrics = compute_metrics(overlay_curve, cfg.initial_capital)

        sharpe_improvement = overlay_metrics.sharpe_ratio - baseline_metrics.sharpe_ratio

        # Crisis annualized returns
        crisis_returns = {}
        for year, rets in crisis_daily_returns.items():
            if rets:
                cumulative = 1.0
                for r in rets:
                    cumulative *= (1 + r)
                crisis_returns[year] = round((cumulative - 1) * 100, 2)

        return BacktestResult(
            total_return=overlay_metrics.total_return,
            cagr=overlay_metrics.cagr,
            volatility=overlay_metrics.volatility,
            sharpe_ratio=overlay_metrics.sharpe_ratio,
            max_drawdown=overlay_metrics.max_drawdown,
            baseline_sharpe=baseline_metrics.sharpe_ratio,
            sharpe_improvement=sharpe_improvement,
            total_rebalances=total_rebalances,
            total_transaction_costs=total_costs,
            crisis_returns={
                "2008": crisis_returns.get("2008"),
                "2020": crisis_returns.get("2020"),
                "2022": crisis_returns.get("2022"),
            },
            extras={
                "overlay_active_days": overlay_active_days,
                "overlay_active_pct": overlay_active_days / len(self.data) * 100 if self.data else 0,
                "collar_active_days": collar_active,
                "vixy_active_days": vixy_active,
                "crypto_active_days": crypto_active,
                "bond_duration_active_days": bond_dur_active,
                "equity_curve": equity_curve_sampled,
            },
        )

    def print_results(self, result: BacktestResult):
        """Print formatted backtest results."""
        logger.info("\n" + "=" * 70)
        logger.info("UNIFIED OVERLAY BACKTEST RESULTS (2006-2026)")
        logger.info("=" * 70)
        logger.info(f"\n  Overlay Portfolio:")
        logger.info(f"    CAGR:              {result.cagr:.2f}%")
        logger.info(f"    Volatility:        {result.volatility:.2f}%")
        logger.info(f"    Sharpe:            {result.sharpe_ratio:.3f}")
        logger.info(f"    Max Drawdown:      {result.max_drawdown:.2f}%")
        logger.info(f"\n  Baseline (46/38/16):")
        logger.info(f"    Sharpe:            {result.baseline_sharpe:.3f}")
        logger.info(f"\n  Delta:")
        logger.info(f"    Sharpe improvement: {result.sharpe_improvement:+.3f}")
        verdict = "POSITIVE" if result.sharpe_improvement > 0 else "NEGATIVE"
        logger.info(f"    Verdict:            {verdict}")
        logger.info(f"\n  Overlay Activity:")
        e = result.extras
        logger.info(f"    Days active:       {e['overlay_active_days']}/{len(self.data)} ({e['overlay_active_pct']:.1f}%)")
        logger.info(f"    Collar days:       {e['collar_active_days']}")
        logger.info(f"    VIXY hedge days:   {e['vixy_active_days']}")
        logger.info(f"    Crypto days:       {e['crypto_active_days']}")
        logger.info(f"    Bond duration days:{e['bond_duration_active_days']}")
        logger.info(f"\n  Trade Stats:")
        logger.info(f"    Rebalances:        {result.total_rebalances}")
        logger.info(f"    Transaction costs: ${result.total_transaction_costs:.2f}")
        crisis = result.crisis_returns or {}
        if any(v is not None for v in crisis.values()):
            logger.info(f"\n  Crisis Performance:")
            if crisis.get("2008") is not None:
                logger.info(f"    2008 return:       {crisis['2008']:.2f}%")
            if crisis.get("2020") is not None:
                logger.info(f"    2020 return:       {crisis['2020']:.2f}%")
            if crisis.get("2022") is not None:
                logger.info(f"    2022 return:       {crisis['2022']:.2f}%")
        logger.info("\n" + "=" * 70)

    def save_results(self, result: BacktestResult, path: Optional[str] = None):
        """Save results to JSON file."""
        from dataclasses import asdict

        out_path = path or str(BACKTEST_RESULTS_DIR / "unified_overlay_results.json")
        data = asdict(result)
        save_results_json(data, output_path=out_path)
        logger.info("Results saved to %s", out_path)


def main():
    import sys
    backtester = UnifiedOverlayBacktester()

    if not backtester.load_data():
        print("Failed to load price data")
        sys.exit(1)

    result = backtester.run()
    backtester.print_results(result)

    if "--save" in sys.argv:
        backtester.save_results(result)


if __name__ == "__main__":
    from src.utils.log_config import configure_logging
    configure_logging()
    main()
