#!/usr/bin/env python3
"""
Portfolio-Lab v3.10 Phase 2: Stacking Ensemble Trainer

XGBoost-based meta-learner training for signal stacking ensemble.
Trains classifier to predict directional accuracy from 102-dimensional
feature vectors generated by StackingFeatureEngine.

Usage:
    python -m src.ml.stacking_trainer train --start-date 2018-01-01
    python -m src.ml.stacking_trainer backfill --dry-run
    python -m src.ml.stacking_trainer evaluate --model models/signal_stacker_v1.json

Performance Targets:
- Training time: <5 minutes for 5 years of daily data
- Validation AUC: >0.72 (vs 0.65 baseline weighted voting)
- Inference latency: <5ms per prediction
"""

import json
import numpy as np
import xgboost as xgb
import sqlite3
import argparse
from typing import Dict, List, Optional, Tuple, NamedTuple
from dataclasses import dataclass, asdict
from datetime import datetime, timedelta
from pathlib import Path
import sys
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report
import logging

project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from src.signals.stacking_feature_engine import StackingFeatureEngine, SignalSource

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class TrainingConfig:
    """Configuration for stacking ensemble training."""
    # XGBoost hyperparameters
    learning_rate: float = 0.05
    max_depth: int = 4
    n_estimators: int = 1000
    early_stopping_rounds: int = 10
    reg_alpha: float = 0.1
    reg_lambda: float = 1.0
    eval_metric: str = "auc"
    
    # Training configuration
    min_training_days: int = 252  # 1 year minimum
    validation_split: float = 0.2
    n_splits: int = 5  # Time series cross-validation folds
    
    # Feature configuration
    feature_count: int = 102
    
    # Data sources
    db_path: str = "data/market.db"
    model_dir: str = "models"
    
    # Target configuration
    prediction_horizon_days: int = 5  # Predict 5-day directional accuracy


@dataclass
class TrainingResult:
    """Results from a training run."""
    model_version: str
    training_date: str
    
    # Performance metrics
    train_accuracy: float
    validation_accuracy: float
    validation_auc: float
    
    # Cross-validation results
    cv_mean_accuracy: float
    cv_std_accuracy: float
    cv_mean_auc: float
    
    # Feature importance
    top_features: List[Tuple[str, float]]
    
    # Data statistics
    training_samples: int
    validation_samples: int
    date_range: Tuple[str, str]
    
    # Model path
    model_path: str


@dataclass  
class PredictionResult:
    """Single prediction result from stacked ensemble."""
    timestamp: str
    prediction: int  # 0 or 1 (correct/incorrect directional call)
    probability: float  # Probability of correct prediction
    confidence: float  # max(probability, 1-probability)
    
    # Feature vector snapshot (for debugging)
    feature_vector: Optional[List[float]] = None
    
    # Fallback indicator
    using_fallback: bool = False
    fallback_reason: str = ""


class StackingTrainer:
    """
    Trains and manages XGBoost meta-learner for signal stacking ensemble.
    
    Handles:
    - Historical data backfill and labeling
    - Time-series cross-validation
    - Model training with early stopping
    - Model versioning and persistence
    - Feature importance extraction
    """
    
    def __init__(self, config: Optional[TrainingConfig] = None):
        self.config = config or TrainingConfig()
        self.feature_engine = StackingFeatureEngine()
        self.model: Optional[xgb.XGBClassifier] = None
        self.model_version: Optional[str] = None
        
        # Ensure model directory exists
        self.model_dir = Path(project_root) / self.config.model_dir
        self.model_dir.mkdir(parents=True, exist_ok=True)
    
    def _load_historical_data(
        self, 
        start_date: str, 
        end_date: Optional[str] = None
    ) -> Tuple[np.ndarray, np.ndarray, List[str]]:
        """
        Load historical signal predictions and realized returns.
        
        Returns:
            X: Feature matrix (n_samples, 102)
            y: Target vector (n_samples,) - 1 if signal was correct, 0 otherwise
            dates: List of dates for each sample
        """
        db_path = Path(project_root) / self.config.db_path
        
        if not db_path.exists():
            logger.warning(f"Database not found at {db_path}, using synthetic data")
            return self._generate_synthetic_data()
        
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        # Check if signal_predictions table exists
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='signal_predictions'
        """)
        
        if not cursor.fetchone():
            logger.warning("signal_predictions table not found, using synthetic data")
            conn.close()
            return self._generate_synthetic_data()
        
        # Load signal predictions
        query = """
            SELECT 
                timestamp, source, signal_value, confidence, 
                predicted_direction, actual_direction
            FROM signal_predictions 
            WHERE timestamp >= ?
        """
        params = [start_date]
        
        if end_date:
            query += " AND timestamp <= ?"
            params.append(end_date)
        
        query += " ORDER BY timestamp, source"
        
        cursor.execute(query, params)
        rows = cursor.fetchall()
        conn.close()
        
        if len(rows) < self.config.min_training_days:
            logger.warning(f"Insufficient data ({len(rows)} rows), using synthetic data")
            return self._generate_synthetic_data()
        
        # Organize by date
        data_by_date: Dict[str, Dict] = {}
        for row in rows:
            date, source, signal_value, confidence, predicted_direction, actual_direction = row
            
            if date not in data_by_date:
                data_by_date[date] = {
                    'signals': {},
                    'actual_direction': actual_direction
                }
            
            data_by_date[date]['signals'][source] = {
                'value': signal_value,
                'confidence': confidence,
                'predicted_direction': predicted_direction
            }
        
        # Build feature matrix and targets
        X_list = []
        y_list = []
        dates = []
        
        for date, data in sorted(data_by_date.items()):
            # Need all 8 signals present
            if len(data['signals']) < 8:
                continue
            
            # Create feature vector
            features = self._create_features_from_signals(data['signals'])
            if features is None:
                continue
            
            # Determine if prediction was correct
            # actual_direction: 0 (down/neutral), 1 (up)
            actual = data['actual_direction']
            
            # Use ensemble prediction direction (simplified: average of signals)
            ensemble_pred = np.mean([
                s['predicted_direction'] 
                for s in data['signals'].values()
            ])
            predicted = 1 if ensemble_pred > 0.5 else 0
            
            # Target: 1 if prediction was correct, 0 otherwise
            target = 1 if predicted == actual else 0
            
            X_list.append(features)
            y_list.append(target)
            dates.append(date)
        
        if len(X_list) < self.config.min_training_days:
            logger.warning(f"Insufficient valid samples ({len(X_list)}), using synthetic data")
            return self._generate_synthetic_data()
        
        return np.array(X_list), np.array(y_list), dates
    
    def _create_features_from_signals(
        self, 
        signals: Dict[str, Dict]
    ) -> Optional[np.ndarray]:
        """Create 102-dimensional feature vector from signal dictionary."""
        # Map string sources to enum
        signal_values = {}
        for source_str, data in signals.items():
            try:
                source = SignalSource(source_str)
                signal_values[source] = data['value']
            except ValueError:
                continue
        
        if len(signal_values) < 8:
            return None
        
        # Use feature engine to generate features
        features = self.feature_engine.generate_feature_vector(signal_values)
        return features
    
    def _generate_synthetic_data(
        self, 
        n_samples: int = 1000
    ) -> Tuple[np.ndarray, np.ndarray, List[str]]:
        """Generate synthetic training data for testing."""
        logger.info(f"Generating {n_samples} synthetic samples")
        
        np.random.seed(42)
        
        # Generate base signal values
        X = np.random.randn(n_samples, self.config.feature_count)
        
        # Generate targets with some correlation to features
        # Feature 0-7 are base signals - make them somewhat predictive
        signal_strength = 0.3
        y_prob = 0.5 + signal_strength * np.tanh(X[:, :8].mean(axis=1))
        y = (np.random.random(n_samples) < y_prob).astype(int)
        
        dates = [
            (datetime(2020, 1, 1) + timedelta(days=i)).strftime('%Y-%m-%d')
            for i in range(n_samples)
        ]
        
        return X, y, dates
    
    def train(
        self, 
        start_date: str = "2018-01-01",
        end_date: Optional[str] = None
    ) -> TrainingResult:
        """
        Train XGBoost meta-learner on historical data.
        
        Args:
            start_date: Training start date (YYYY-MM-DD)
            end_date: Training end date (defaults to today)
            
        Returns:
            TrainingResult with metrics and model path
        """
        if end_date is None:
            end_date = datetime.now().strftime('%Y-%m-%d')
        
        logger.info(f"Loading historical data from {start_date} to {end_date}")
        X, y, dates = self._load_historical_data(start_date, end_date)
        
        logger.info(f"Loaded {len(y)} samples")
        
        # Time-series cross-validation
        tscv = TimeSeriesSplit(n_splits=self.config.n_splits)
        cv_scores = []
        cv_aucs = []
        
        for fold, (train_idx, val_idx) in enumerate(tscv.split(X)):
            X_train, X_val = X[train_idx], X[val_idx]
            y_train, y_val = y[train_idx], y[val_idx]
            
            fold_model = xgb.XGBClassifier(
                learning_rate=self.config.learning_rate,
                max_depth=self.config.max_depth,
                n_estimators=self.config.n_estimators,
                early_stopping_rounds=self.config.early_stopping_rounds,
                reg_alpha=self.config.reg_alpha,
                reg_lambda=self.config.reg_lambda,
                eval_metric=self.config.eval_metric,
                random_state=42
            )
            
            fold_model.fit(
                X_train, y_train,
                eval_set=[(X_val, y_val)],
                verbose=False
            )
            
            y_pred = fold_model.predict(X_val)
            y_prob = fold_model.predict_proba(X_val)[:, 1]
            
            acc = accuracy_score(y_val, y_pred)
            auc = roc_auc_score(y_val, y_prob)
            
            cv_scores.append(acc)
            cv_aucs.append(auc)
            
            logger.info(f"Fold {fold+1}: Accuracy={acc:.3f}, AUC={auc:.3f}")
        
        # Train final model on all data
        logger.info("Training final model on all data")
        self.model = xgb.XGBClassifier(
            learning_rate=self.config.learning_rate,
            max_depth=self.config.max_depth,
            n_estimators=self.config.n_estimators,
            early_stopping_rounds=self.config.early_stopping_rounds,
            reg_alpha=self.config.reg_alpha,
            reg_lambda=self.config.reg_lambda,
            eval_metric=self.config.eval_metric,
            random_state=42
        )
        
        # Use last 20% as validation for early stopping
        split_idx = int(len(X) * 0.8)
        X_train, X_val = X[:split_idx], X[split_idx:]
        y_train, y_val = y[:split_idx], y[split_idx:]
        
        self.model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            verbose=False
        )
        
        # Final evaluation
        y_train_pred = self.model.predict(X_train)
        y_val_pred = self.model.predict(X_val)
        y_val_prob = self.model.predict_proba(X_val)[:, 1]
        
        train_accuracy = accuracy_score(y_train, y_train_pred)
        val_accuracy = accuracy_score(y_val, y_val_pred)
        val_auc = roc_auc_score(y_val, y_val_prob)
        
        logger.info(f"Final - Train Accuracy: {train_accuracy:.3f}")
        logger.info(f"Final - Val Accuracy: {val_accuracy:.3f}")
        logger.info(f"Final - Val AUC: {val_auc:.3f}")
        
        # Extract feature importance
        importance = self.model.feature_importances_
        feature_names = self._get_feature_names()
        
        top_indices = np.argsort(importance)[-10:][::-1]
        top_features = [
            (feature_names[i], float(importance[i]))
            for i in top_indices
        ]
        
        logger.info("Top 5 features:")
        for name, imp in top_features[:5]:
            logger.info(f"  {name}: {imp:.3f}")
        
        # Save model using pickle for XGBClassifier
        import pickle
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        model_version = f"v{timestamp}"
        model_path = self.model_dir / f"signal_stacker_{model_version}.pkl"
        
        with open(model_path, 'wb') as f:
            pickle.dump(self.model, f)
        logger.info(f"Model saved to {model_path}")
        
        # Create result
        result = TrainingResult(
            model_version=model_version,
            training_date=datetime.now().isoformat(),
            train_accuracy=train_accuracy,
            validation_accuracy=val_accuracy,
            validation_auc=val_auc,
            cv_mean_accuracy=np.mean(cv_scores),
            cv_std_accuracy=np.std(cv_scores),
            cv_mean_auc=np.mean(cv_aucs),
            top_features=top_features,
            training_samples=len(y_train),
            validation_samples=len(y_val),
            date_range=(dates[0], dates[-1]),
            model_path=str(model_path)
        )
        
        # Save training result
        result_path = self.model_dir / f"training_result_{model_version}.json"
        with open(result_path, 'w') as f:
            json.dump(asdict(result), f, indent=2)
        
        self.model_version = model_version
        return result
    
    def _get_feature_names(self) -> List[str]:
        """Generate feature names for interpretability."""
        names = []
        sources = list(SignalSource)
        
        # Base signals (0-7)
        for source in sources:
            names.append(f"base_{source.value}")
        
        # Pairwise interactions (8-91)
        # Use combinations from itertools to get all pairs
        from itertools import combinations
        pairs = list(combinations(sources, 2))
        pairs_sorted = sorted(pairs, key=lambda x: (x[0].value, x[1].value))
        
        for s1, s2 in pairs_sorted:
            names.append(f"mult_{s1.value[:3]}_{s2.value[:3]}")
            names.append(f"disagree_{s1.value[:3]}_{s2.value[:3]}")
            names.append(f"avg_{s1.value[:3]}_{s2.value[:3]}")
        
        # Regime context (92-93)
        names.extend(["vix_normalized", "trend_strength"])
        
        # Historical accuracy (94-101)
        for source in sources:
            names.append(f"hist_acc_{source.value[:3]}")
        
        return names
    
    def load_model(self, model_path: str) -> bool:
        """Load a trained model from disk."""
        import pickle
        path = Path(model_path)
        if not path.exists():
            logger.error(f"Model not found: {model_path}")
            return False
        
        with open(path, 'rb') as f:
            self.model = pickle.load(f)
        
        # Extract version from filename
        self.model_version = path.stem.replace("signal_stacker_", "")
        
        logger.info(f"Loaded model {self.model_version}")
        return True
    
    def predict(
        self, 
        features: np.ndarray,
        confidence_threshold: float = 0.6
    ) -> PredictionResult:
        """
        Make prediction from feature vector.
        
        Args:
            features: 102-dimensional feature vector
            confidence_threshold: Minimum confidence for using prediction
            
        Returns:
            PredictionResult with probability and fallback indicators
        """
        if self.model is None:
            return PredictionResult(
                timestamp=datetime.now().isoformat(),
                prediction=0,
                probability=0.5,
                confidence=0.5,
                using_fallback=True,
                fallback_reason="No model loaded"
            )
        
        # Ensure features is 2D
        if features.ndim == 1:
            features = features.reshape(1, -1)
        
        # Get prediction probability
        prob = self.model.predict_proba(features)[0, 1]
        prediction = 1 if prob >= 0.5 else 0
        confidence = max(prob, 1 - prob)
        
        # Check confidence threshold
        using_fallback = confidence < confidence_threshold
        fallback_reason = "" if not using_fallback else f"Confidence {confidence:.3f} < {confidence_threshold}"
        
        return PredictionResult(
            timestamp=datetime.now().isoformat(),
            prediction=prediction,
            probability=float(prob),
            confidence=float(confidence),
            feature_vector=features[0].tolist(),
            using_fallback=using_fallback,
            fallback_reason=fallback_reason
        )
    
    def backfill_predictions(
        self,
        start_date: str = "2018-01-01",
        dry_run: bool = False
    ) -> Dict:
        """
        Backfill predictions for historical data.
        
        Args:
            start_date: Start date for backfill
            dry_run: If True, don't save to database
            
        Returns:
            Statistics dict with counts and performance
        """
        logger.info(f"Backfilling predictions from {start_date}")
        
        X, y, dates = self._load_historical_data(start_date)
        
        if self.model is None:
            logger.error("No model loaded for backfill")
            return {"error": "No model loaded"}
        
        # Generate predictions
        predictions = []
        fallback_count = 0
        
        for i, (features, actual, date) in enumerate(zip(X, y, dates)):
            result = self.predict(features)
            
            if result.using_fallback:
                fallback_count += 1
            
            correct = (result.prediction == actual)
            
            predictions.append({
                'date': date,
                'prediction': result.prediction,
                'probability': result.probability,
                'confidence': result.confidence,
                'actual': actual,
                'correct': correct,
                'fallback': result.using_fallback
            })
        
        accuracy = sum(p['correct'] for p in predictions) / len(predictions)
        fallback_rate = fallback_count / len(predictions)
        
        logger.info(f"Backfill complete: {len(predictions)} predictions")
        logger.info(f"  Accuracy: {accuracy:.3f}")
        logger.info(f"  Fallback rate: {fallback_rate:.3f}")
        
        if not dry_run:
            self._save_backfill_predictions(predictions)
        
        return {
            'total_predictions': len(predictions),
            'accuracy': accuracy,
            'fallback_count': fallback_count,
            'fallback_rate': fallback_rate,
            'date_range': (dates[0], dates[-1])
        }
    
    def _save_backfill_predictions(self, predictions: List[Dict]):
        """Save backfilled predictions to database."""
        db_path = Path(project_root) / self.config.db_path
        db_path.parent.mkdir(parents=True, exist_ok=True)
        
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        # Create table if not exists
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS stacking_predictions (
                date TEXT PRIMARY KEY,
                prediction INTEGER,
                probability REAL,
                confidence REAL,
                actual INTEGER,
                correct INTEGER,
                fallback INTEGER,
                model_version TEXT
            )
        """)
        
        # Insert predictions
        for pred in predictions:
            cursor.execute("""
                INSERT OR REPLACE INTO stacking_predictions 
                (date, prediction, probability, confidence, actual, correct, fallback, model_version)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                pred['date'], pred['prediction'], pred['probability'],
                pred['confidence'], pred['actual'], int(pred['correct']),
                int(pred['fallback']), self.model_version
            ))
        
        conn.commit()
        conn.close()
        
        logger.info(f"Saved {len(predictions)} predictions to database")


def main():
    parser = argparse.ArgumentParser(description="Stacking Ensemble Trainer")
    parser.add_argument(
        'command',
        choices=['train', 'evaluate', 'backfill', 'list'],
        help='Command to execute'
    )
    parser.add_argument('--start-date', default='2018-01-01', help='Start date')
    parser.add_argument('--end-date', help='End date')
    parser.add_argument('--model', help='Model path for evaluation')
    parser.add_argument('--dry-run', action='store_true', help='Dry run mode')
    
    args = parser.parse_args()
    
    trainer = StackingTrainer()
    
    if args.command == 'train':
        result = trainer.train(args.start_date, args.end_date)
        print(json.dumps(asdict(result), indent=2))
        
    elif args.command == 'evaluate':
        if not args.model:
            print("Error: --model required for evaluate")
            return
        success = trainer.load_model(args.model)
        if not success:
            return
        print(f"Model {trainer.model_version} loaded successfully")
        
    elif args.command == 'backfill':
        if not trainer.model:
            # Try to load latest model
            model_files = sorted(trainer.model_dir.glob("signal_stacker_v*.json"))
            if model_files:
                trainer.load_model(str(model_files[-1]))
            else:
                print("No model found for backfill")
                return
        
        stats = trainer.backfill_predictions(args.start_date, args.dry_run)
        print(json.dumps(stats, indent=2))
        
    elif args.command == 'list':
        model_files = sorted(Path(project_root / 'models').glob("signal_stacker_*.json"))
        print(f"Available models ({len(model_files)}):")
        for mf in model_files:
            print(f"  {mf.name}")


if __name__ == '__main__':
    main()
